version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    groups:
      dev-tooling:
        patterns:
          - black
          - mypy
          - pylint
          - pytest*
          - ruff
          - types-*
          - vulture

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
